#!/bin/bash

#bash scriptListe https://members.loria.fr/BWrobelDautcourt/publications/
#https://members.loria.fr/MDuflot/files/publis.html

#il doit y avoir un argument
if [ $#==1 ] ; then
	wget -O document.txt $1
	awk 'BEGIN{RS=" "; FS="\""} /^href=.*[.]pdf/{print $2;}' document.txt > listePDF.txt
	awk 'BEGIN{FS="\"";RS=" "} /^href=.*[.]pdf/{lastPDF=NR;} /href=.*/ && lastPDF!=NR{print $2;}' document.txt > ad-hoc.txt
	awk 'BEGIN{RS=" "; FS="\""} /^href=.*[.]loria[.]/{print $2;}' document.txt  > visite.txt
#la ligne de commande n'est pas correct
else
    echo "le nomnre d'argument doit être de 1"
fi
