#!/bin/bash

lecture () {

    cat $1 | awk '{print $3}' | while read lien ; do
	cp ../scriptUrl ./
	bash scriptUrl $lien
    done
}

if [ $# -ne 1 ] ; then
    echo " le nombre d'argument doit être de 1"
    exit 1
fi

cat $1 | awk '{print $1$2}' | while read nom ; do
    mkdir -p $nom
    cd $nom
    cp ../$1 ./
    lecture $1
    rm $1
    cd ../
done
